version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: nosql-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: nosql_media
    volumes:
      - mongodb_data:/data/db
      - ./server/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - nosql-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nosql-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/nosql_media?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-here
      PORT: 3000
    volumes:
      - ./server/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - nosql-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nosql-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - nosql-network

volumes:
  mongodb_data:

networks:
  nosql-network:
    driver: bridge